# Generated by Django 3.2.5 on 2021-08-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='companyname',
            new_name='compname',
        ),
    ]
