# Generated by Django 3.2.5 on 2021-08-31 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_rename_companyname_experience_compname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='compname',
            new_name='companyname',
        ),
    ]
