# Generated by Django 3.2.5 on 2021-08-31 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_auto_20210831_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='companyname',
        ),
    ]
