# Generated by Django 3.2.5 on 2021-08-31 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_remove_experience_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='companyname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
