# Generated by Django 3.2.5 on 2021-08-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_alter_experience_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='worklocation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
