# Generated by Django 3.2.5 on 2021-09-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0008_experience_worklocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='companydescription',
            field=models.CharField(blank=True, max_length=550),
        ),
        migrations.AlterField(
            model_name='experience',
            name='jobdescription',
            field=models.CharField(blank=True, max_length=5550),
        ),
    ]
